### ISSUE TITLE
A little issue about run EDAPGui

### ISSUE THREAD

**Issue by Kaminingyo** [SumZer0-git/EDAPGui#35]
Excuse me ,how could I just ban update check? 

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 416, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/SumZer0-git/EDAPGui/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EDAPGui.py", line 772, in <module>
    main()
  File "EDAPGui.py", line 767, in main
    app = APGui(root)
  File "EDAPGui.py", line 181, in __init__
    self.check_updates()
  File "EDAPGui.py", line 301, in check_updates
    response = requests.get("https://api.github.com/repos/SumZer0-git/EDAPGui/releases/latest")
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/SumZer0-git/EDAPGui/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by SumZer0-git** [comment]
In front of line 301 in EDAPGui.py    you could put:  “return” so that it won’t execute the check . From: KaminingyoSent: Sunday, May 7, 2023 2:51 AMTo: SumZer0-git/EDAPGuiCc: SubscribedSubject: [SumZer0-git/EDAPGui] A little issue about run EDAPGui (Issue #35) Excuse me ,how could I just ban update check?Traceback (most recent call last):File "urllib3\connectionpool.py", line 703, in urlopenFile "urllib3\connectionpool.py", line 386, in make_requestFile "urllib3\connectionpool.py", line 1040, in validate_connFile "urllib3\connection.py", line 416, in connectFile "urllib3\util\ssl.py", line 449, in ssl_wrap_socketFile "urllib3\util\ssl.py", line 493, in _ssl_wrap_socket_implFile "ssl.py", line 500, in wrap_socketFile "ssl.py", line 1040, in _createFile "ssl.py", line 1309, in do_handshakessl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)During handling of the above exception, another exception occurred:Traceback (most recent call last):File "requests\adapters.py", line 440, in sendFile "urllib3\connectionpool.py", line 785, in urlopenFile "urllib3\util\retry.py", line 592, in incrementurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/SumZer0-git/EDAPGui/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))During handling of the above exception, another exception occurred:Traceback (most recent call last):File "EDAPGui.py", line 772, in main()File "EDAPGui.py", line 767, in mainapp = APGui(root)File "EDAPGui.py", line 181, in initself.check_updates()File "EDAPGui.py", line 301, in check_updatesresponse = requests.get("https://api.github.com/repos/SumZer0-git/EDAPGui/releases/latest")File "requests\api.py", line 75, in getFile "requests\api.py", line 61, in requestFile "requests\sessions.py", line 529, in requestFile "requests\sessions.py", line 645, in sendFile "requests\adapters.py", line 517, in sendrequests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/SumZer0-git/EDAPGui/releases/latest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
