### ISSUE TITLE
Please help to install

### ISSUE THREAD

**Issue by Schn1tz1** [SumZer0-git/EDAPGui#47]
Hey there,

I really appreciate your work. Sadly I am completly not into coding and python.

You mean default HUD colours in ED right?
So my screen resolution needs to be at 3440 and /1440? Only ingame or with Windows?
With focus you mean to only run ED, right?
How do I install needed requirements? I downloaded auto mix prep for example and clicked on the setup.py, but nothing happens.
Advanced Autodocking" module must be outfitted on ship to support autodock: Where do I get that from?
Can not find the autopilot.log file or the .exe
Nothing happens when starting the EDAPGui.py

I know these are many questions, but I hope you can help me, as I really need those features in ED.

Kind Regards

**Comment by SumZer0-git** [comment]
You mean default HUD colours in ED right?
E0 - yes, the HUD

So my screen resolution needs to be at 3440 and /1440? Only ingame or with Windows?
E0 - I too use 3440x1440 so you should be good.   But should be both ingame and Windows config

With focus you mean to only run ED, right?
E0- yes.  focus meaning if you do mouse/keyboard/HOTAS those events go to the game, 


How do I install needed requirements? I downloaded auto mix prep for example and clicked on the setup.py, but nothing happens.
E0 - "pip install -r requirements.txt"      is the command.   Of course python must be installed first

Advanced Autodocking" module must be outfitted on ship to support autodock: Where do I get that from?
E0 - correct.   You should be able to find it at most stations.  You can use inara.cz to search for a station that provides it

Can not find the autopilot.log file or the .exe
E0 - if you download the release it includes the executable.  That said, the executable is older but still works.  I need to schedule some time to make a new release with the executable to bring in all the latest updates.   The autopilot.log file is created the first time you run and should be in the directory you are running from

Nothing happens when starting the EDAPGui.py
E0- Do you get the AP window display?

I suggest you jump over to discord:  https://discord.gg/HCgkfSc     There is a community there that can help

**Comment by SumZer0-git** [comment]
.
